apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the deployment resource, used to identify and manage it
  name: swear-stop-frontend
  labels:
    # Label categorizing the application as part of the frontend
    tier: frontend
    # Layer tag to help manage different application components (e.g., backend, frontend)
    layer: website
spec:
  # Number of pod replicas (only 1 instance for now)
  replicas: 1
  selector:
    # Selector to match the pods created by this deployment based on labels
    matchLabels:
      tier: frontend
      layer: website
  template:
    metadata:
      labels:
        # Labels to associate with the pod created by this deployment
        tier: frontend
        layer: website
    spec:
      # InitContainer to run migrations before the main application container starts
      initContainers:
        - name: swear-stop-frontend-migrations
          # Docker image containing the Laravel app that will run the migrations
          image: danukawaidyatillake/text-moderator-frontend-app:v0.0.4
          command:
            - php
          args:
            # Command to run Laravel migrations
            - artisan
            - migrate
          # Environment variables loaded from a ConfigMap and Secret for secure configuration
          envFrom:
            - configMapRef:
                # Refers to the ConfigMap that contains environment configurations
                name: swear-stop-frontend-config
            - secretRef:
                # Refers to the Secret that contains sensitive data like database credentials
                name: swear-stop-frontend-secret

      containers:
        - name: swear-stop-frontend
          # Docker image for the main frontend application
          image: danukawaidyatillake/text-moderator-frontend-app:v0.0.4
          # Exposing port 80 for web traffic
          ports:
            - containerPort: 80
          env:
            # Setting the FPM host environment variable to communicate with the backend
            - name: FPM_HOST
              value: localhost:9000
          # Additional environment variables pulled from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: swear-stop-frontend-config
            - secretRef:
                name: swear-stop-frontend-secret
